language: php

branches:
  except:
    - /^release-\d+\.\d+\.\d+.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - laminas-mkdoc-theme

env:
  global:
    - SITE_URL: https://docs.laminas.dev/laminas-xmlrpc
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/laminas/laminas-xmlrpc.git
    - secure: "tE/9gTe0U+QN1mlCC7Wr70RaOHn3Mtn8ZZTjN0LuhDhXTe3Hs197DNNv3vxNSXRavIRuLi1mIEiEu1uzV4qlnUx01Uj+G+jCshYLrZIQ8TxVJEXB1r1tFrNosg4s1hpxDQn7O5O0VzOEB8G01PobCUmPNTDPGi77xj8HyE+SCLQPnnNPwp4gJtifS+bBOmAe//A0aOA14ArzJLi4xfEKCC2yoSUawob8xX9LbMfLwq8/IEPYtLqN9rvk5qpc2/uhb7Hrqk7Nq8Xt6Gv2ixgDkfYup7BswAamtT5M4m02mXBneYqC2OYDeuStv8kkaIIjTCKxOOPzseRgHJgXLxnRNbJjG7fLaTpWYtl4ZqevGZlp+GrRGHMsQO4wxXMAM0U476nLzNlQDw3xEH9dKpf/QRM1bsP2b45fxHRklRjek+KXIF0bE7q5+jkOeHzg/z05CF6EMSjZuuI+qoUrdZub/R6pTxwhqBzDzUxZjTY3gj5+qlTlvn/B18tCXNsHjsFX75Boy1ST45ai/6ow1veyaWk9H/wIJEqEk54gWDsonpwpGgQjQcoZ58QRi9SKxv0hBFB+No+k2fFnQc0pvTJKa/3Pk+k2I77BvaqtZxC6eqXHKOiDvaR/ywBAIPLBEHL7Fm4Xeu80voNAPlcRV+5qD7ptPaV6gxqeNm1rM81SZHA="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - CS_CHECK=true
    - php: 5.6
      env:
        - TEST_COVERAGE=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 7
    - php: hhvm 
  allow_failures:
    - php: hhvm

notifications:
  email: false

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - travis_retry composer self-update

install:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; fi
  - if [[ $TEST_COVERAGE != 'true' ]]; then composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/laminas/laminas-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./laminas-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi
