docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Intro: intro.md
    - Reference:
        - "XML-RPC Clients": client.md
        - "XML-RPC Servers": server.md
site_name: laminas-xmlrpc
site_description: laminas-xmlrpc
repo_url: 'https://github.com/laminas/laminas-xmlrpc'
