docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
    - Reference:
        - "XML-RPC Clients": client.md
        - "XML-RPC Servers": server.md
site_name: zend-xmlrpc
site_description: "Fully-featured XML-RPC server and client implementations"
repo_url: 'https://github.com/zendframework/zend-xmlrpc'
